=== klozn/java-sep-2021-tdd/30-enterprise-software-development-java/30-web-services/20-SOAP-XML/10-xml/codelab10/phoneContacts.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="phoneContacts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="contact" type="person" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="person">
        <xs:all>
            <xs:element name="firstname" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="lastname" type="xs:string" />
            <xs:element name="birthDate" type="xs:date" />
            <xs:element name="phoneNumber">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="isMobileNumber" type="xs:boolean" default="false"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== klozn/java-sep-2021-tdd/30-enterprise-software-development-java/30-web-services/20-SOAP-XML/10-xml/codelab10/phoneContacts01.xml
<?xml version="1.0" encoding="UTF-8" ?>
<phoneContacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="phoneContacts.xsd" >
    <contact>
        <lastname>Murdoch</lastname>
        <birthDate>1956-05-12</birthDate>
        <phoneNumber isMobileNumber="true">0485546213</phoneNumber>
    </contact>
    <contact>
        <lastname>Bezos</lastname>
        <birthDate>2013-11-30</birthDate>
        <phoneNumber>85412168</phoneNumber>
        <firstname>Jeff</firstname>
    </contact>
</phoneContacts>
