=== klozn/java-sep-2021-tdd/30-enterprise-software-development-java/30-web-services/20-SOAP-XML/10-xml/solutions/phoneContacts_alternative.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://switchfully.com"
           xmlns="https://switchfully.com"
           elementFormDefault="qualified">

    <!-- an XML instance containing as its root element a person element,
    can be validate against to XML Schema now as well -->
    <xs:element name="person">
        <xs:complexType>
            <xs:all>
                <xs:element name="firstname" minOccurs="0">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="lastname" type="xs:string"/>
                <xs:element name="birthDate" type="xs:date"/>
                <xs:element name="phoneNumber" type="phoneNumberType"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="phoneNumberType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="isMobileNumber" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="phoneContacts">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="person" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== klozn/java-sep-2021-tdd/30-enterprise-software-development-java/30-web-services/20-SOAP-XML/10-xml/solutions/phoneContacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<phoneContacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://switchfully.com phoneContacts_alternative.xsd"
               xmlns="https://switchfully.com">
    <person>
        <firstname>Jim</firstname>
        <birthDate>1980-12-25</birthDate>
        <lastname>Jimmens</lastname>
        <phoneNumber>484510452</phoneNumber>
    </person>
    <person>
        <birthDate>1985-10-20</birthDate>
        <lastname>Timmens</lastname>
        <phoneNumber>475523489</phoneNumber>
    </person>
    <person>
        <firstname>An</firstname>
        <lastname>Andrews</lastname>
        <birthDate>1988-03-15</birthDate>
        <phoneNumber isMobileNumber="true">477588120</phoneNumber>
    </person>
</phoneContacts>
